services:
  db:
    image: postgres:16
    container_name: finalshop-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: finalshop
      POSTGRES_PASSWORD: finalshop
      POSTGRES_DB: finalshop
    ports:
      - "5432:5432"
    volumes:
      - finalshop_db:/var/lib/postgresql/data

volumes:
  finalshop_db:
